/**
 
INSERT INTO skills (skill_name, description) VALUES
("JavaScript", "A versatile programming language for web development."),
("Python", "A high-level programming language popular for data science and web development."),
("Java", "A widely-used programming language known for its platform independence."),
("C#", "A modern, object-oriented programming language developed by Microsoft."),
("C++", "A high-performance programming language used for system/software development."),
("HTML5", "The latest version of HTML, used for structuring content on the web."),
("CSS3", "Cascading Style Sheets, used to design and layout web pages."),
("SQL", "A standard language used for managing and querying relational databases."),
("NoSQL", "Non-relational databases that store data in a variety of formats."),
("React", "A JavaScript library for building user interfaces, primarily for web apps."),
("Vue.js", "A progressive JavaScript framework for building user interfaces."),
("Angular", "A platform for building mobile and desktop web applications using TypeScript."),
("Node.js", "A runtime environment that allows JavaScript to be run on the server side."),
("Express.js", "A minimalist web framework for Node.js, ideal for building web APIs."),
("Ruby", "A dynamic, open-source programming language known for its simplicity."),
("PHP", "A popular server-side scripting language used for web development."),
("Swift", "A programming language developed by Apple for building iOS and macOS applications."),
("Kotlin", "A statically typed programming language used for Android app development."),
("TypeScript", "A superset of JavaScript that adds static typing to the language."),
("Flutter", "A UI toolkit from Google to build natively compiled applications for mobile, web, and desktop."),
("Git", "A version control system for tracking changes in source code during software development."),
("Docker", "A tool designed to make it easier to create, deploy, and run applications by using containers."),
("AWS", "Amazon Web Services, a comprehensive and widely adopted cloud platform."),
("Azure", "Microsoft's cloud computing service offering a wide range of cloud services."),
("Google Cloud", "Google's cloud platform that provides infrastructure, application development, and cloud-based services."),
("DevOps", "A culture and set of practices that bring together software development and IT operations."),
("CI/CD", "Continuous Integration and Continuous Deployment, practices for automating code integration and delivery."),
("GraphQL", "A query language for your API, and a runtime for executing those queries with your existing data."),
("REST API", "An architectural style for designing networked applications, relying on stateless communication."),
("Jenkins", "An open-source automation server that supports building, deploying, and automating software projects."),
("Sass", "A preprocessor scripting language that is interpreted or compiled into CSS."),
("Webpack", "A module bundler for JavaScript applications, often used with React and Angular."),
("JQuery", "A fast, small, and feature-rich JavaScript library that simplifies HTML document traversal."),
("Bootstrap", "A front-end framework for building responsive, mobile-first websites."),
("Tailwind CSS", "A utility-first CSS framework for rapidly building custom user interfaces."),
("SEO", "Search Engine Optimization, the practice of optimizing websites to rank better in search engine results."),
("UI/UX Design", "The design of user interfaces and user experiences to create visually appealing and functional websites or apps."),
("Figma", "A collaborative design tool for UI/UX design, prototyping, and wireframing."),
("Photoshop", "A graphics editing program used for creating, editing, and enhancing visual designs."),
("Illustrator", "A vector graphics editor used to create scalable illustrations and designs."),
("Agile Methodology", "A project management methodology for software development that emphasizes iterative progress."),
("Scrum", "An Agile framework for developing, delivering, and sustaining complex products.");


 */